### ISSUE TITLE
Directory separator incorrectly used for URL in getResizedImageUrl()

### ISSUE THREAD

**Issue by clivewalkden** [staempfli/magento2-module-image-resizer#14]
Hi,

On Windows machines the use of the directory separator in getRelativePathResizedImage() which is called within getResizedImageUrl causes issues as URL's are generated in the following format.

`http://domain.com/media/staempfli_imageresizer\cache\wysiwyg\638x372_co_ar_tr_85\filename.jpg`

Suggest changing DIRECTORY_SEPARATOR to just use '/' for full OS support.

Shall I do a PR for this?

**Comment by jalogut** [comment]
Hi @clivewalkden,

Yes, a PR would be appreciated. Thanks

**Comment by clivewalkden** [comment]
Tested on my Windows machine and URL is now correctly output

**Comment by jalogut** [comment]
Fixed on version `2.0.2`
