### ISSUE TITLE
Original Image is used when using CDN

### ISSUE THREAD

**Issue by johnny-longneck** [staempfli/magento2-module-image-resizer#17]
Yesterday we switched to a CDN (Cloudfront). It works fine but the resized images via this module are wrong. It is always outputting the original image path, which leads to a page speed disaster right now.

Updated to latest version 2.0.2 
Magento 2.2.4
PHP7
Varnish
Nginx

Expected Output:

`<img src="https://d2rblablablaqf.cloudfront.net/staempfli_imageresizer/cache/catalog/category/182x182_co_ar_tr/niceimage.png" >`

Actual Output

`<img src="https://d2rblablablaqf.cloudfront.net/catalog/category/niceimage.png" />`

**Comment by mbernabeu** [comment]
Hi @jalogut!!

this pull request solves this  #19

**Comment by jalogut** [comment]
Issue is fixed in version `2.0.3`
