### ISSUE TITLE
fopen with url error

### ISSUE THREAD

**Issue by adamvarga** [staempfli/magento2-module-image-resizer#22]
Hi,

I updated your extension to 2.1.0 and I had problem in the frontend by every category page:
(I use Magento Community Edition 2.2.7.)

`2019-03-18 09:54:58] main.CRITICAL: Warning: fopen(<<url>>): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in <<url>>/src/vendor/staempfli/magento2-module-image-resizer/Model/Resizer.php on line 315 [] []`

I think: ` $filepointer = fopen($file, "rb");` fopen with urls is usaually disallowed on productions servers

With the version 2.0.3 I don't have problem.

Can you fix it?

Best regards,
Adam

**Comment by lumnn** [comment]
I'm having similar issue. On my setup I use self-signed SSL certificates for development purposes and the recent breakes development because it fails on SSL verification

**Comment by audef1** [comment]
Fixed by removing 2.1.0 ;)

**Comment by bacondeveloper** [comment]
Works with 2.0.3, however 2.1 is still on Packagist so it is still getting 2.1 unless you explicitly say 2.0.3 in composer.json
