### ISSUE TITLE
initRelativeFilenameFromUrl doesn't take into account cdn url

### ISSUE THREAD

**Issue by gtlt** [staempfli/magento2-module-image-resizer#4]
Resizer doesn't work if you have a media url different from your imageUrl.
Example :
base site : www.example.com => base of the imageUrl
media url : cdn.example.com => strpos fails

fix => use the parse_url function

**Comment by gtlt** [comment]
I made a pull request : https://github.com/staempfli/magento2-module-image-resizer/pull/5

**Comment by jalogut** [comment]
Hi @gtlt 

Thanks for your contribution. I merged the PR and added a small change in your code. You can find these changes on version 1.1
